import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton
} from '@clerk/nextjs';
import syncUser from './actions/syncUser';
import { currentUser } from '@clerk/nextjs/server';
import { redirect } from 'next/navigation';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

// app/layout.tsx
import Link from 'next/link';
import { Home, LayoutGrid, User } from 'lucide-react'; // Pro icons

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();
  if (user) {
    await syncUser(user);
  }

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0b0e14] text-white`}
        >
          <header className="flex justify-between items-center px-8 py-4 border-b border-gray-800 bg-[#0b0e14]/80 backdrop-blur-md sticky top-0 z-50">
            <div className="flex items-center gap-8">
              {/* Logo */}
              <Link href="/" className="group flex items-center gap-2">
                <div className="bg-blue-600 p-1.5 rounded-lg group-hover:rotate-12 transition-transform">
                  <span className="text-white font-black text-xl leading-none">
                    N
                  </span>
                </div>
                <h1 className="text-xl font-bold tracking-tighter text-white">
                  NextChat
                </h1>
              </Link>

              {/* Navigation Links */}
              <nav className="hidden md:flex items-center gap-1">
                <Link
                  href="/"
                  className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium text-gray-400 hover:text-white hover:bg-gray-800 transition-all"
                >
                  <Home className="h-4 w-4" />
                  Home
                </Link>

                <Link
                  href="/rooms"
                  className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium text-gray-400 hover:text-white hover:bg-gray-800 transition-all"
                >
                  <LayoutGrid className="h-4 w-4" />
                  Rooms
                </Link>

                {/* New Profile Link */}
                <SignedIn>
                  <Link
                    href="/profile"
                    className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium text-gray-400 hover:text-white hover:bg-gray-800 transition-all"
                  >
                    <User className="h-4 w-4" />
                    Profile
                  </Link>
                </SignedIn>
              </nav>
            </div>

            {/* Auth section */}
            <div className="flex items-center gap-4">
              <SignedIn>
                <div className="flex items-center gap-3 pr-2 border-r border-gray-800 mr-2 hidden sm:flex">
                  <span className="text-xs text-gray-500 font-medium">
                    {user?.firstName}
                  </span>
                </div>
                <UserButton afterSignOutUrl="/" />
              </SignedIn>

              <SignedOut>
                <SignInButton mode="modal">
                  <button className="bg-blue-600 hover:bg-blue-700 text-white px-5 py-2 rounded-xl text-sm font-bold shadow-lg shadow-blue-500/20 transition-all active:scale-95">
                    Sign In
                  </button>
                </SignInButton>
              </SignedOut>
            </div>
          </header>

          <main className="min-h-[calc(100vh-73px)]">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
